"""Initial migration

Revision ID: 229eeead42bc
Revises: 
Create Date: 2024-02-12 18:38:48.014643

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '229eeead42bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation')
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['id'])

    with op.batch_alter_table('time', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.alter_column('times',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('time_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.alter_column('times',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('id')

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('date',
               existing_type=sa.String(length=50),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.drop_column('customer_id')

    op.create_table('reservation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('court_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['court_id'], ['court.id'], name='reservation_court_id_fkey'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='reservation_customer_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='reservation_pkey')
    )
    # ### end Alembic commands ###
